name: Deploy React App and API to Ionos

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install Dependencies
      run: npm ci
      
    - name: Build React App
      run: CI=false npm run build
      
    # First deploy PHP API files
    - name: Deploy PHP API files
      uses: wangyucode/sftp-upload-action@v1.4.8
      with:
        host: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 22
        localDir: './'  # Root directory to find PHP files
        remoteDir: '/kunden/homepages/26/d4298754775/htdocs/'
        forceUpload: true
        dryRun: false
        # Only include PHP files and any other API-related files
        include: |
          *.php
          db_connect.php
          tmdb_api.php
    
    # Then deploy React build files
    - name: Deploy React build
      uses: wangyucode/sftp-upload-action@v1.4.8
      with:
        host: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 22
        localDir: './build/'
        remoteDir: '/kunden/homepages/26/d4298754775/htdocs/'
        forceUpload: true
        dryRun: false