name: Deploy React App with API Directory

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install Dependencies
      run: npm ci
      
    - name: Build React App
      run: CI=false npm run build
      
    - name: Prepare API Directory
      run: |
        # Create api directory inside build
        mkdir -p build/api
        
        # Copy all PHP files to the api directory
        cp *.php build/api/
        
        # If you need to exclude certain PHP files from being moved to api
        # You can do that with specific commands
        # Example: mv build/api/index.php build/ (if you have a PHP index file that should stay in root)
        
        # List files to verify
        echo "Files in build/api directory:"
        ls -la build/api/
    
    - name: Deploy to Ionos
      uses: wangyucode/sftp-upload-action@v1.4.8
      with:
        host: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 22
        localDir: './build/'
        remoteDir: '/Movie-Maker/'
        forceUpload: true
        dryRun: false