name: Deploy React App with API to Ionos

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install Dependencies
      run: npm ci
      
    - name: Build React App
      run: CI=false npm run build
      
    - name: Copy API Files to Build
      run: |
        # Debug repository structure
        echo "Repository structure:"
        ls -la
        
        if [ -d "api" ]; then
          echo "Found api directory, copying contents to build/api"
          mkdir -p build/api
          cp -r api/* build/api/
          echo "Files copied to build/api:"
          ls -la build/api/
        else
          echo "api directory not found. Searching for PHP files..."
          mkdir -p build/api
          find . -name "*.php" -type f -not -path "./build/*" -not -path "./node_modules/*" | while read file; do
            echo "Copying $file to build/api/"
            cp "$file" build/api/
          done
          
          echo "Files in build/api directory:"
          ls -la build/api/
        fi
    
    - name: Create db_connect.php with Secrets
      run: |
        # Create db_connect.php with credentials from GitHub Secrets
        cat > build/api/db_connect.php << EOL
        <?php
          \$host_name = '${{ secrets.DB_HOST }}';
          \$database = '${{ secrets.DB_NAME }}';
          \$user_name = '${{ secrets.DB_USER }}';
          \$password = '${{ secrets.DB_PASSWORD }}';

          \$conn = new mysqli(\$host_name, \$user_name, \$password, \$database);

          if (\$conn->connect_error) {
            die('<p>Failed to connect to MySQL: '. \$conn->connect_error .'</p>');
          }
        ?>
        EOL
        
        # Ensure the file has the right permissions
        chmod 644 build/api/db_connect.php
        
        echo "Created db_connect.php with secure credentials"
        echo "Final list of files in build/api:"
        ls -la build/api/
    
    - name: Deploy to Ionos
      uses: wangyucode/sftp-upload-action@v1.4.8
      with:
        host: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 22
        localDir: './build/'
        remoteDir: '/Movie-Maker/'
        forceUpload: true
        dryRun: false