name: Deploy React App with API Files

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install Dependencies
      run: npm ci
      
    - name: Build React App
      run: CI=false npm run build
      
    - name: Debug Repository Structure
      run: |
        echo "Repository structure:"
        ls -la
        echo "Contents of api directory (if exists):"
        ls -la api/ || echo "api directory not found at root level"
        echo "Searching for api directory:"
        find . -type d -name "api" | grep -v "node_modules" || echo "No api directory found in project"
        
    - name: Copy API Files to Build
      run: |
        # If api directory exists, copy its contents to build/api
        if [ -d "api" ]; then
          echo "Found api directory at root level, copying contents to build/api"
          mkdir -p build/api
          cp -r api/* build/api/
          echo "Files copied to build/api:"
          ls -la build/api/
        else
          echo "Searching for API files in the repository..."
          # Create the destination directory
          mkdir -p build/api
          
          # Try to find and copy PHP files
          find . -name "*.php" -type f -not -path "./build/*" -not -path "./node_modules/*" | while read file; do
            echo "Copying $file to build/api/"
            cp "$file" build/api/
          done
          
          echo "Files in build/api directory:"
          ls -la build/api/
        fi
    
    - name: Deploy to Ionos
      uses: wangyucode/sftp-upload-action@v1.4.8
      with:
        host: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 22
        localDir: './build/'
        remoteDir: '/Movie-Matcher/'
        forceUpload: true
        dryRun: false