name: Deploy React App with API Directory

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install Dependencies
      run: npm ci
      
    - name: Build React App
      run: CI=false npm run build
      
    - name: Prepare API Directory with Debug Info
      run: |
        # Create api directory inside build
        mkdir -p build/api
        
        # Debug: List all PHP files in repo root
        echo "PHP files in repository root:"
        ls -la *.php || echo "No PHP files found with wildcard"
        
        # Copy PHP files individually to ensure they're all copied
        echo "Copying specific PHP files to api directory..."
        cp create_session.php build/api/ || echo "Failed to copy create_session.php"
        cp db_connect.php build/api/ || echo "Failed to copy db_connect.php"
        cp get_matches.php build/api/ || echo "Failed to copy get_matches.php"
        cp get_movies.php build/api/ || echo "Failed to copy get_movies.php"
        cp join_session.php build/api/ || echo "Failed to copy join_session.php"
        cp save_preference.php build/api/ || echo "Failed to copy save_preference.php"
        cp test-db.php build/api/ || echo "Failed to copy test-db.php"
        cp tmdb_api.php build/api/ || echo "Failed to copy tmdb_api.php"
        cp update_session.php build/api/ || echo "Failed to copy update_session.php"
        
        # Verify files in api directory
        echo "Files in build/api directory after copying:"
        ls -la build/api/
    
    - name: Deploy to Ionos
      uses: wangyucode/sftp-upload-action@v1.4.8
      with:
        host: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 22
        localDir: './build/'
        remoteDir: '/Movie-Matcher/'
        forceUpload: true
        dryRun: false